server {
    listen 80;
    server_name htcai.local;

    location /assets/ {
        proxy_pass http://app:80/assets/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://app:80/a/htcai/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
    }
}

server {
    listen 80;
    server_name tecneuralai.local;

    location /assets/ {
        proxy_pass http://app:80/assets/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://app:80/a/tecneuralai/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
    }
}