server {
    listen 80;
    server_name htcai.local;

    location / {
        proxy_pass http://app:3000/a/htcai;
    }
}

server {
    listen 80;
    server_name tecneuralai.local;

    location / {
        proxy_pass http://app:3000/a/tecneuralai;
    }
}